<a href="https://colab.research.google.com/github/Chay-spec/tres-bien/blob/main/L_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.shape #is use to check the shape of the array

(4, 1)

In [ ]:
a=a.reshape(4,1) #reshaping in matrix form.
#or
a=a.reshape(1,4)
#or
a=a.reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.array([1,43,5])
b.shape

(3,)

In [ ]:
b=b.reshape(1,3) #2d array
#or
b=b.reshape(3,1,1)#3d array
b.shape

(3, 1, 1)

# DOT


This function returns the dot product of two arrays.For 2-D vactors,it is the equivalenet of the matrixmultiplication . For 1-D arrays,it is the inner product of the vectors. For N-dimensional, it is the sum product over the last axis of a and the second axis of b

In [11]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print("a:", a)
print()
print("b:", b)
np.dot(a,b)
#[1*5+2*7 1*6+2*8] [3*5+4*7 3*6+4*8]

a: [[1 2]
 [3 4]]

b: [[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

# Random Function

syntax: numpy.random.random(size=None)

---


Parameters:

---
size:[int or tuple of ints,optional]


---


output shape: if the given shape is e.g.,(m,n,k),then m,n,k samples are drawn

In [14]:
#out_arr
out_arr=np.random.random(size=2)
print("Output of 1-d array filled with random floats: ", out_arr)






Output of 1-d array filled with random floats:  [0.73427138 0.86338875]


In [15]:
np.random.random((2,3))

array([[0.62614949, 0.97121646, 0.88017367],
       [0.41515256, 0.18872378, 0.10283774]])

# Slicing

In [18]:
a=np.random.random((2,3))
a

array([[0.59376669, 0.72629809, 0.56397311],
       [0.09406077, 0.48505758, 0.76214979]])

In [25]:
a[:,:-1]

array([[0.59376669, 0.72629809],
       [0.09406077, 0.48505758]])

In [26]:
a[1:3,1:3]

array([[0.48505758, 0.76214979]])

# Sum function()

numpy.sum(arr,axis,dtype,out):

---


This function returns the sum of array over the specific axiz

In [27]:
#1d array
arr=[20,2,.2,10,4]
print("sum of arr: ", np.sum(arr))

sum of arr:  36.2


In [32]:
arr=np.array([[0,5],[0,3]]) #2d array
print(arr)
np.sum(arr,axis=0)

[[0 5]
 [0 3]]


array([0, 8])

# Square function()
Ths element helps user to calculate the square value of each element in the array

In [34]:
arr1=[1,3,-9,-11]
print("square of the array:\n", np.square(arr1))

square of the array:
 [  1   9  81 121]
